### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by rashray** [cloudmesh-community/hid-sp18-417#3]
- [ ] Docker on WIndows
 - [ ] Install docker on ubuntu16.04
- [ ] Read scientific writing section-... 
- [ ] Setting up one of the Pi's as a DHCP server ... 
- [ ] LaTeX and jabref module from the hand book
- [ ] Big Data Applications Section from the hand book
- [ ] Cloudmesh Command Shell from the hand book
- [ ] creating a dockerfile for LaTeX  - piazza
- [ ] Residential Students Pi cluster tutorials - piazza
- [ ] Cloudmesh command shell - handbook
- [ ] Hadoop spark - handbook
